name: Continuous Integration
on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:
jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop --display-cop-names
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Markdown
      uses: actionshub/markdownlint@1.2.0
    - name: Check links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
