name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  rubocop:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Ruby
      uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
      with:
        ruby-version: '3.3'
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop --display-cop-names
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Lint Markdown
      uses: actionshub/markdownlint@6c82ff529253530dfbf75c37570876c52692835f # v3.1.4
    - name: Check links
      uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
