name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  rubocop:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop --display-cop-names
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Markdown
      uses: actionshub/markdownlint@1.2.0
    - name: Check links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
